name: s3craftings
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 플러터 앱 버전
# 안드로이드와 iOS의 버전을 맞추기 위해 사용
# 하위 버전을 보장하지 않을 때에는 맨 앞쪽 번호를 변경
# ex) 2.0.0 -> 3.0.0
# 중요한 업데이트는 가운데 번호를 변경
# ex) 1.0.0 -> 1.1.0
# 소규모 업데이트는 맨 마지막 번호를 변경
# ex) 1.0.0 -> 1.0.1
# 빌드 번호/hotfix 는 +1씩 증가
version: 1.0.0+1


# flutter 버전
environment:
  sdk: '>=3.3.2 <4.0.0'


# 외부 라이브러리를 넣을때 사용
# 빌드했을 때 같이 묶여서 나감
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  cached_network_image: ^3.2.3

# 테스트 코드를 작성할 때 사용
# 개발 시점에 필요함
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
